## YAML Template.
---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
    
server:
  port: 48154
  
custom:
  activeprofileName: Production
  
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:transaction
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
